on: [push]

jobs:
  update_python_version:
    runs-on: ubuntu-latest
    name: A job to update python
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: iwootten/update-python-version@v1
        id: update-python
      - name: Create Pull Request
        if: ${{ steps.update-python.outputs.updated = true }}
        uses: peter-evans/create-pull-request@v2
        with: 
          commit-message: "Update .python-version to ${{ steps.update-python.outputs.latest-version }}"
          title: Update .python-version to ${{ steps.update-python.outputs.latest-version }}