on:
  push:
    branches:
      - master

jobs:
  update_python_version:
    runs-on: ubuntu-latest
    name: A job to update python
    steps:
      - uses: actions/checkout@v2
      - uses: iwootten/update-pyenv@v1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2.7.1
        with:
          commit-message: "Update to latest python version"
          title: Update .python-version